//
//  UserViewModel.swift
//  NatureID
//
//  Created by MacNCheese on 13/09/2023.
//

import Foundation
import SwiftUI
import FirebaseAuth
import FirebaseFirestore
import FirebaseFirestoreSwift

class SessionManager : ObservableObject{
    @Published var user : User?
    @Published var isLoading = false
    
    let db = Firestore.firestore()
    let auth = Auth.auth()
    init() {
        self.auth.addStateDidChangeListener { auth, user in
            if let user = user {
                self.getUser(id: user.uid)
            }else {
                withAnimation {
                    self.user = nil
                }
            }
        }
    }
    
    
    
    func register(email : String, userName : String, password : String, image : UIImage, completion: @escaping (String?) -> Void) {
        if(userName.isEmpty) {
            completion("Please enter a username")
            return
        }
        isLoading = true
        
        // MARK: create new user
        auth.createUser(withEmail: email, password: password){ authResult, error in
            if error != nil{
                completion(error!.localizedDescription)
                self.isLoading = false
                return
            }
            if let authResult = authResult {
                var newUser = User()
                let currentUser = authResult.user
                
                newUser.id = currentUser.uid
                newUser.email = currentUser.email
                newUser.userName = userName
                // Upload image
                ImageManager.upload(image: image, name: currentUser.uid) { url in
                    if let url = url{
                        newUser.photoUrl = url.absoluteString
                        self.createUser(user: newUser)
                    }else {
                        self.isLoading = false
                        completion("Upload image failed")
                        return
                    }
                }
            }else {
                self.isLoading = false
                completion("Register failed")
                return
            }
            self.isLoading = false
            completion(nil)
        }
    }
    
    func login(email : String, password : String, completion: @escaping (String?) -> Void) {
        isLoading = true
        auth.signIn(withEmail: email, password: password) { authResult, error in
            self.isLoading = false
            if(error != nil){
                print(error!)
                completion(error!.localizedDescription)
                return
            }
            if authResult != nil {
                completion(nil)
                return
            }
            completion("Error logging in")
        }
    }
    
    func logout() {
        do {
            try auth.signOut()
        } catch {
            print(error)
        }
    }
    
    func createUser(user : User){
        // ID generated by Firebase Auth
        do {
            isLoading = true
            try db.collection("user").document(user.id!).setData(from: user, completion: { error in
                if let error = error{
                    print(error.localizedDescription)
                }
                self.isLoading = false
            })
        } catch {
            isLoading = false
            print(error.localizedDescription)
        }
    }
    
    func getUser(id : String) {
        self.isLoading = true
        db.collection("user").document(id).addSnapshotListener { docSnapshot, error in
            self.isLoading = false
            if(error != nil){
                print(error!.localizedDescription)
                return
            }
            
            do {
                guard let doc = try docSnapshot?.data(as: User.self) else {return}
                withAnimation {
                    self.user = doc
                }
            }catch {
                print(error.localizedDescription)
            }
        }
    }
}
